apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: nats-poc
  labels:
    app: mongo
spec:
  selector:
    matchLabels:
      app: mongo
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo
        version: v1
    spec:
      containers:
        - name: mongo
          image: mongo
          imagePullPolicy: Always
          resources:
            limits:
              memory: 1Gi
            requests:
              cpu: 250m
          ports:
            - containerPort: 27017