apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats
  namespace: nats-poc
  labels:
    app: nats
spec:
  selector:
    matchLabels:
      app: nats
  replicas: 1
  template:
    metadata:
      labels:
        app: nats
        version: v1
    spec:
      containers:
        - name: nats
          image: nats:2.2.0-alpine
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 250m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 512Mi
          ports:
            - containerPort: 4222
            - containerPort: 6222
            - containerPort: 8222
          volumeMounts:
            - name: application-config
              mountPath: "/etc/nats"
          command:
            - "nats-server"
            - "--config"
            - "/etc/nats/nats-server.conf"
            - "-DV"
      volumes:
        - name: application-config
          configMap:
            name: nats
            items:
              - key: nats-server.conf
                path: nats-server.conf